--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/lenlenlL6/Anti-Advertisement
build-by-default: true
branches:
- main
projects:
  Anti-Advertisement:
    path: ""
    icon: "icon.png"
...
